version: '3.7'

services:
  php-apache:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ungexternaldatabseurlmo.oregon-postgres.render.com # renderdb name
      DB_PORT: 5432
      DB_NAME: databsase # Replace with actual DB name
      DB_USER: todo_32kx_user       # username
      DB_PASSWORD: passwordmo   # Replace with actual password
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4  # Google's DNS

networks:
  app-network:
    driver: bridge
